<?php

namespace Application;


class Forum extends WebApplication
{
    use UserTrait;
    use MaterialsTrait;

    /**
     * @var array
     */
    private $topics = array(array('theme' => "Vasy_Pupkin",
        'text' => 'Hello! Lets disquss..'
    ),
        array('theme' => "daisy",
            'text' => 'Hello! Lets disquss..'
        )
    );

    /**
     * @var array
     */

    function __construct($url, $name, $server, $materials, $topics, $usersInfo)
    {
        $this->setURL($url);
        $this->setName($name);
        $this->setServer($server);
        $this->materials = $materials;
        $this->topics = $topics;
        $this->usersInfo = $usersInfo;
    }


    /**
     * @return array
     */
    public function getTopics()
    {
        return $this->topics;
    }

    /**
     * @param array $topics
     */
    public function setTopics($topics)
    {
        $this->topics = $topics;
    }


    protected function giveInformation()
    {
        return parent::giveInformation(); // TODO: Change the autogenerated stub
    }


} 