<?php
/**
 * Created by PhpStorm.
 * User: varrek
 * Date: 02.05.14
 * Time: 16:37
 */

namespace Application;


class PublicPage extends WebApplication implements HackableInterface
{
    use MaterialsTrait;

    /**
     * @var string
     */
    private $publications;

    function __construct($url = "http://imaginarium.in.ua", $name = "Igor Kozlov blog", $server = "NGINX", $publications = array('Steve Vai', 'Metallica official page'))
    {
        $this->setSecurityCoef(rand(0, 6));
        $this->setURL($url);
        $this->setName($name);
        $this->setServer($server);
        $this->publications = $publications;
    }

    /**
     * @return string
     */
    public function getPublications()
    {
        return $this->publications;
    }

    /**
     * @param string $publications
     */
    public function setPublications($publications)
    {
        $this->publications = $publications;
    }

    /**
     * @return mixed
     */
    public function giveInformation()
    {
        return parent::giveInformation(); // TODO: Change the autogenerated stub
    }

    public function isHackable()
    {
        return true;
    }
}