<?php
/**
 * Created by PhpStorm.
 * User: varrek
 * Date: 02.05.14
 * Time: 16:37
 */

namespace Application;


class PublicPage extends WebApplication{
    use MaterialsTrait;

    /**
     * @var string
     */
    private $publications;

    function __construct($publications)
    {
        $this->publications = $publications;
    }

    /**
     * @return string
     */
    public function getPublications()
    {
        return $this->publications;
    }

    /**
     * @param string $publications
     */
    public function setPublications($publications)
    {
        $this->publications = $publications;
    }

    /**
     * @return mixed
     */
    protected function giveInformation()
    {
        return parent::giveInformation(); // TODO: Change the autogenerated stub
    }

} 