<?php

namespace Application;


class SocialNetwork extends WebApplication
{
    use UserTrait;
    use MaterialsTrait;

    /**
     * @var array
     */
    private $messages = array(array('from' => "Vasy_Pupkin",
        'to' => 'daisy',
        'text' => 'Hello!'
    ),
        array('from' => "daisy",
            'to' => 'Vasyliy Pupkin',
            'text' => 'Hello!'
        )
    );

    private $groups = array(
        'Steve Vai', 'Metallica official page', 'Symfony community', 'NetCop'
    );

    private $communityApplications = array(
        'Happy Farm', 'Poker', 'Nano Farm'
    );

    function __construct($url, $name, $server, $communityApplications, $groups, $messages)
    {
        $this->setURL($url);
        $this->setName($name);
        $this->setServer($server);
        $this->communityApplications = $communityApplications;
        $this->groups = $groups;
        $this->messages = $messages;
    }


    /**
     * @return array
     */
    public function getMessages()
    {
        return $this->messages;
    }

    /**
     * @param array $messages
     */
    public function setMessages($messages)
    {
        $this->messages = $messages;
    }

    /**
     * @return array
     */
    public function getCommunityApplications()
    {
        return $this->communityApplications;
    }

    /**
     * @param array $communityApplications
     */
    public function setCommunityApplications($communityApplications)
    {
        $this->communityApplications = $communityApplications;
    }

    /**
     * @return array
     */
    public function getGroups()
    {
        return $this->groupes;
    }

    /**
     * @param array $groups
     */
    public function setGroups($groups)
    {
        $this->groupes = $groups;
    }


    protected function giveInformation()
    {
        return parent::giveInformation(); // TODO: Change the autogenerated stub
    }


} 