bionic_university_unusedcss_homepage:
    pattern:  /
    defaults: { _controller: BionicUniversityUnusedcssBundle:Default:index }
bionic_university_unusedcss_crawl:
    path:     /crawl
    defaults: { _controller: BionicUniversityUnusedcssBundle:Test:crawl }
bionic_university_unusedcss_test_create:
    path:     /crawl/create
    defaults: { _controller: BionicUniversityUnusedcssBundle:Test:create }
bionic_university_unusedcss_test_list:
    path:     /tests/list
    defaults: { _controller: BionicUniversityUnusedcssBundle:Test:list }
bionic_university_unusedcss_test_show:
    pattern:  /{id}/show
    defaults: { _controller: BionicUniversityUnusedcssBundle:Test:show }
