parameters:
    bionic_university_unusedcss.urlCrawler.class: BionicUniversity\UnusedcssBundle\Services\UrlCrawlerService

services:
    bionic_university_unusedcss.agregator:
       class: %bionic_university_unusedcss.urlCrawler.class%
       arguments:  [%site_url%]
