parameters:
#    bionic_university_unusedcss.example.class: BionicUniversity\UnusedcssBundle\Example

services:
#    bionic_university_unusedcss.example:
#        class: %bionic_university_unusedcss.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
