bionic_university_user:
    resource: "@BionicUniversityUserBundle/Resources/config/routing.yml"
    prefix:   /

bionic_university_unusedcss:
    resource: "@BionicUniversityUnusedcssBundle/Resources/config/routing.yml"
    prefix:   /

