security:
    access_control:
      - { path: ^/secure_area, roles: ROLE_USER }
    encoders:
      BionicUniversity\UserBundle\Entity\User:
                algorithm:        sha1
                encode_as_base64: false
                iterations:       1
    role_hierarchy:
       ROLE_ADMIN:       ROLE_USER
       ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        in_db:
                entity: { class: BionicUniversityUserBundle:User, property: username   }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                    login_path:  login
                    check_path:  login_check
            logout:
                    path:   /logout
                    target: /
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~